version: "3.9"

services:


  server:
    build: .

    container_name: chess-server

    ports:
      - "3000:3000"

    environment:
      - MONGO_URI=mongodb+srv://dasiedu_db_user:0VQ1YgzP2AYHHuh1@cluster0.zhboaqd.mongodb.net/?appName=mun-chess
