version: "3.9"

services:
  server:
    build: .
    container_name: chess-server
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/chessdb

  mongo:
    image: mongo:7
    container_name: chess-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
